version: '3.7'
services:
  BlogDB:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=blogdb'
      - 'MYSQL_USER=bloguser'
      - 'MYSQL_PASSWORD=blogpassword'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - ./mysqldata:/var/lib/mysql